simplemooc/simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	path(
		'login/', 
		auth_views.login, 
		{'template_name': 'accounts/login.html'},
		name = 'login'
	),
	path(
		'register/',
		views.register,
		name = 'register'
	),
	path(
		'logout/',
		auth_views.logout,
		{'next_page': 'core:home'},
		name = 'logout'
	),
	path(
		'dashboard/',
		views.dashboard,
		name = 'dashboard'
	),
	path(
		'edit/',
		views.edit,
		name = 'edit'
	),
	path(
		'edit/password',
		views.edit_password,
		name = 'edit_password'
	)
]

simplemooc/simplemooc/core/urls.py
from django.urls import path
from . import views  

app_name = 'core'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('contact/', views.contact, name = 'contact')
]

simplemooc/simplemooc/courses/urls.py
from django.urls import path, re_path
from . import views  

app_name = 'courses'

urlpatterns = [
    path('', views.courses, name = 'index'),
    #re_path(r'^details/(?P<id>\d+)/$', views.details, name = 'details')
    re_path(r'^details/(?P<slug>[\w_-]+)/$', views.details, name = 'details')
]

simplemooc/simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simplemooc.core.urls')),
    path('courses/', include('simplemooc.courses.urls')),
    path('accounts/', include('simplemooc.accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/core/models.py
from django.db import models

app_name = 'accounts'

simplemooc/simplemooc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
	return render(request, 'home.html', {'title' : 'Home - Django - Desenvolvimento WEB com Python'})

def contact(request):
	return render(request, 'contact.html', {'title' : 'Entre em contato - Django - Desenvolvimento WEB com Python'})

simplemooc/simplemooc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
        <title>
            {{title}}
        </title>
        <link rel="stylesheet" href="{% static 'css/pure/pure-min.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    </head>
    <body>
        <div class="content">
            <div class="header">
                <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
                    <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
                    <ul>
                        <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
                        <li><a href="{% url 'courses:index' %}">Cursos</a></li>
                        <li><a href="{% url 'core:contact' %}">Contato</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'accounts:dashboard' %}">Painel</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:login' %}">Acessar conta</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            {% block content %} {% endblock %}
            <div class="footer">
                Simple MOOC - Uma simples plataforma de ensino a distância
            </div>
        </div>
        <script src="{% static 'js/yui/yui-min.js' %}"></script>
    </body>
</html>

simplemooc/simplemooc/core/templates/contact.html
{% extends 'base.html' %}
    {% block content %}
                <div class="pure-g-r content-ribbon">
                    <div class="pure-u-2-3">
                        <div class="l-box">
                            <h4 class="content-subhead">
                                Entre em contato
                            </h4>
                            <h3>
                                Utilize os dados abaixo para entrar em contato
                            </h3>
                            <p>
                                Email: contato@dgmtisolucoes.com
                            </p>
                            <p>
                                Telefone: (31) 9990-3296
                            </p>
                        </div>
                    </div>
                </div>
    {% endblock %}

simplemooc/simplemooc/core/templates/home.html
{% extends 'base.html' %}		
	{% block content %}
	    <div class="splash">
	        <div class="pure-g-r">
	            <div class="pure-u-1">
	                <div class="l-box splash-text">
	                    <h1 class="splash-head">
	                        Uma Simples Plataforma de Ensino a Distância
	                    </h1>
	                    <h2 class="splash-subhead">
	                        O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
	                    </h2>
	                    <p>
	                        <a href="#" class="pure-button primary-button">Saiba mais</a>
	                    </p>
	                </div>
	            </div>
	        </div>
	    </div>
	    <div class="content">
	        <div class="pure-g-r content-ribbon">
	            <div class="pure-u-2-3">
	                <div class="l-box">
	                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
	                    <h3>Publique suas aulas</h3>
	                    <p>
	                        O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
	                    </p>
	                </div>
	            </div>
	            <div class="pure-u-1-3">
	                <div class="l-box">
	                    <img src="http://placehold.it/400x250"
	                         alt="Vídeo aulas e materiais digitais.">
	                </div>
	            </div>
	        </div>
	        <div class="pure-g-r content-ribbon">
	            <div class="pure-u-1-3">
	                <div class="l-box">
	                    <img src="http://placehold.it/400x250"
	                         alt="Fórum de Dúvidas">
	                </div>
	            </div>
	            <div class="pure-u-2-3">
	                <div class="l-box">
	                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
	                    <h3>Interaja com seus Alunos</h3>
	                    <p>
	                        No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
	                    </p>
	                </div>
	            </div>
	        </div>
	        <div class="pure-g-r content-ribbon">
	            <div class="pure-u-2-3">
	                <div class="l-box">
	                    <h4 class="content-subhead">Exercícios</h4>
	                    <h3>Crie exercícios para avaliar seus alunos</h3>
	                    <p>
	                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
	                    </p>
	                </div>
	            </div>
	            <div class="pure-u-1-3">
	                <div class="l-box">
	                    <img src="http://placehold.it/400x250"
	                         alt="Exercícios">
	                </div>
	            </div>
	        </div>
	        <div class="pure-g-r content-ribbon">
	            <div class="pure-u-1-3">
	                <div class="l-box">
	                    <img src="http://placehold.it/400x250"
	                         alt="Mural de Avisos">
	                </div>
	            </div>
	            <div class="pure-u-2-3">
	                <div class="l-box">
	                    <h4 class="content-subhead">Mural de Avisos</h4>
	                    <h3>Envie anúncios diretamente para os alunos</h3>
	                    <p>
	                        Organize os avisos do seu curso de forma fácil e simples.
	                    </p>
	                </div>
	            </div>
	        </div>
	    </div>	
	{% endblock %}