simplemooc/simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	path(
		'login/', 
		auth_views.login, 
		{'template_name': 'accounts/login.html'},
		name = 'login'
	),
	path(
		'register/',
		views.register,
		name = 'register'
	),
	path(
		'logout/',
		auth_views.logout,
		{'next_page': 'core:home'},
		name = 'logout'
	),
	path(
		'dashboard/',
		views.dashboard,
		name = 'dashboard'
	),
	path(
		'edit/',
		views.edit,
		name = 'edit'
	),
	path(
		'edit/password',
		views.edit_password,
		name = 'edit_password'
	)
]

simplemooc/simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simplemooc.core.urls')),
    path('courses/', include('simplemooc.courses.urls')),
    path('accounts/', include('simplemooc.accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/accounts/models.py
from django.db import models

# Create your models here.

simplemooc/simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

	email = forms.EmailField(
		label = 'Email:'
	)

	first_name = forms.CharField(
		label = 'Nome:',
		max_length = 100
	)

	last_name = forms.CharField(
		label = 'Sobrenome:',
		max_length = 100
	)

	age = forms.DecimalField(
		label = 'Idade:',
		max_digits = 2
	)

	def clean_email(self):
		email = self.cleaned_data['email']

		if User.objects.filter(email = email).exists():
			raise forms.ValidationError('Email já utilizado!')
		else:
			return email

	def clean_age(self):
		age = self.cleaned_data['age']

		if age < 18:
			raise forms.ValidationError('É preciso ser maior de idade!')
		else:
			return age

	def save(self, commit = True):
		user = super(UserCreationForm, self).save(commit = False)
		
		user.username = self.cleaned_data['username']
		user.email = self.cleaned_data['email']
		user.set_password(self.cleaned_data['password1'])
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.age = self.cleaned_data['age']

		if commit:
			user.save()
		return user

class EditAccountForm(forms.ModelForm):

	def clean_email(self):
		email = self.cleaned_data['email']

		queryset = User.objects.filter(email = email).exclude(id = self.instance.id)
		
		if queryset.exists():
			raise forms.ValidationError('Email já utilizado!')
		else:
			return email

	def clean_age(self):
		age = self.cleaned_data['age']

		if age < 18:
			raise forms.ValidationError('É preciso ser maior de idade!')
		else:
			return age

	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email']

simplemooc/simplemooc/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .forms import RegisterForm, EditAccountForm

@login_required
def dashboard(request):

	template_name = 'accounts/dashboard.html'
	context = {}
	
	return render(request, template_name, context)

def register(request):
	
	template_name = 'accounts/register.html'
	
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		
		if form.is_valid():			
			user = form.save()
			user = authenticate(
				username = user.username,
				password = form.cleaned_data['password1']
			)
			login(request, user)
			return redirect(settings.LOGIN_REDIRECT_URL)
	else:
		form = RegisterForm()

	context = {
		'form': form
	}
	
	return render(request, template_name, context)

@login_required
def edit(request):

	template_name = 'accounts/edit.html'
	context = {}

	if request.method == 'POST':
		
		form = EditAccountForm(request.POST, instance = request.user)

		if form.is_valid():
			
			form.save()
			form = EditAccountForm(instance = request.user)
			
			context = {
				'success': True,
				'form': form
			}
	else:
		
		form = EditAccountForm(instance = request.user)
		context = {
			'form': form
		}

	return render(request, template_name, context)

@login_required
def edit_password(request):

	template_name = 'accounts/edit_password.html';
	context = {}

	if request.method == 'POST':

		form = PasswordChangeForm(data = request.POST, user = request.user)

		if form.is_valid():
			
			form.save()
			form = PasswordChangeForm(user = request.user)
			
			context['success'] = True
	else:
		
		form = PasswordChangeForm(user = request.user)
		
	context['form'] = form

	return render(request, template_name, context);

simplemooc/simplemooc/accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li>
                <a href="{% url 'accounts:dashboard' %}">
                    Meu Painel
                </a>
            </li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <a class="pure-menu-heading">Meus Cursos</a>
            <ul>
                <li><a href="#">Curso 1</a></li>
                <li><a href="#">Curso 2</a></li>
                <li class="pure-menu-heading">Minha Conta</li>
                <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
                <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <p><strong>Nome</strong>: {{user.username}}</p>
            <p><strong>E-mail</strong>: {{user.email}}</p>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}
{% block breadcrumb %}
    {{ block.super }}
    <li>
        <a href="{% url 'accounts:edit' %}">
            Editar Conta
        </a>
    </li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>
        Os dados foram alterados com sucesso!
    </p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/simplemooc/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados de cadastro</h2>
            <form class="pure-form pure-form-stacked" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="pure-control-group">
                        <label for="name">
                            {{ field.label_tag }}
                        </label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                    </div>
                </fieldset>
                <p>
                    Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                    Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
                </p>
            </form>
        </div>
    </div>
    {% endblock %}

simplemooc/simplemooc/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados para criar uma nova conta</h2>
            <form class="pure-form pure-form-stacked" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="pure-control-group">
                        <label for="name">
                            {{ field.label_tag }}
                        </label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                    </div>
                </fieldset>
                <p>
                    Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                    Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
                </p>
            </form>
        </div>
    </div>
    {% endblock %}